services:
  api:
    build:
      target: develop
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./packages/api:/code/packages/api
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}