services:
  api:
    build:
      target: develop
      context: .
      dockerfile: ./packages/api/Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./packages/api:/code/packages/api
    environment:
      - POSTGRES_DB=galley
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  database:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=galley
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  data: